const ORDINARY_DRINK = 'Ordinary Drink';
export const drinksAPI = {
  drinks: [
    {
      idDrink: '15997',
      strDrink: 'GG',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: ORDINARY_DRINK,
      strIBA: null,
      strAlcoholic: 'Optional alcohol',
      strGlass: 'Collins Glass',
      strInstructions: 'Pour the Galliano liqueur over ice. Fill the remainder of ...',
      strInstructionsES: null,
      strInstructionsDE: 'Den Galliano-Likör über Eis gießen. Füllen Sie ...',
      strInstructionsFR: null,
      strInstructionsIT: 'Versare il liquore Galliano su ghiaccio.\r\nRiempi...',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/vyxwut1468875960.jpg',
      strIngredient1: 'Galliano',
      strIngredient2: 'Ginger ale',
      strIngredient3: 'Ice',
      strMeasure1: '2 1/2 shots ',
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-07-18 22:06:00',
    },
    {
      idDrink: '17222',
      strDrink: 'A1',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Cocktail',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Cocktail glass',
      strInstructions: 'Pour all ingredients into a cocktail shak..',
      strInstructionsFR: null,
      strInstructionsIT: 'Versar...',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/2x8thr1504816928.jpg',
      strIngredient1: 'Gin',
      strIngredient2: 'Grand Marnier',
      strIngredient3: 'Lemon Juice',
      strIngredient4: 'Grenadine',
      strMeasure1: '1 3/4 shot ',
      strMeasure2: '1 Shot ',
      strMeasure3: '1/4 Shot',
      strMeasure4: '1/8 Shot',
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-07 21:42:09',
    },
  ],
};

export const drinksCategory = {
  drinks: [
    {
      strCategory: ORDINARY_DRINK,
    },
    {
      strCategory: 'Cocktail',
    },
    {
      strCategory: 'Shake',
    },
    {
      strCategory: 'Other/Unknown',
    },
    {
      strCategory: 'Cocoa',
    },
    {
      strCategory: 'Shot',
    },
    {
      strCategory: 'Coffee / Tea',
    },
    {
      strCategory: 'Homemade Liqueur',
    },
    {
      strCategory: 'Punch / Party Drink',
    },
    {
      strCategory: 'Beer',
    },
    {
      strCategory: 'Soft Drink',
    },
  ],
};

export const drinksShake = {
  drinks: [
    {
      strDrink: '151 Florida Bushwacker',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/rvwrvv1468877323.jpg',
      idDrink: '14588',
    },
    {
      strDrink: 'Avalanche',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/uppqty1472720165.jpg',
      idDrink: '16419',
    },
  ],
};

export const chocolateCoffee = {
  drinks: [
    {
      idDrink: '16082',
      strDrink: 'Almond Chocolate Coffee',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: ORDINARY_DRINK,
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Coffee mug',
      strInstructions: 'Pour in order into coffee cup. Top with whipped....',
      strInstructionsES: 'Verter en orden en la taza de café. Cubra con....',
      strInstructionsDE: 'In Reihenfolge in die Kaffeetasse gießen. Mit....',
      strInstructionsFR: null,
      strInstructionsIT: 'Versare in ordine in una tazzina da caffè......',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/jls02c1493069441.jpg',
      strIngredient1: 'Amaretto',
      strIngredient2: 'Dark Creme de Cacao',
      strIngredient3: 'Coffee',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '3/4 oz ',
      strMeasure2: '1/2 oz ',
      strMeasure3: '8 oz ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-04-24 22:30:41',
    },
  ],
};
