export const ingredientFood = {
  meals: [
    {
      strMeal: 'Big Mac',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/urzj1d1587670726.jpg',
      idMeal: '53013',
    },
    {
      strMeal: 'Cream Cheese Tart',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/wurrux1468416624.jpg',
      idMeal: '52779',
    }],
};

export const nameFood = {
  meals: [
    {
      idMeal: '53013',
      strMeal: 'Big Mac',
      strDrinkAlternate: null,
      strCategory: 'Beef',
      strArea: 'American',
      strInstructions: 'For the Big Mac sauce, combine all the ingredients in...',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/urzj1d1587670726.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=C5J39YnnPsg',
      strIngredient1: 'Minced Beef',
      strIngredient2: 'Olive Oil',
      strIngredient3: 'Sesame Seed Burger Buns',
      strIngredient4: 'Onion',
      strIngredient5: 'Iceberg Lettuce',
      strIngredient6: 'Cheese',
      strIngredient7: 'Dill Pickles',
      strIngredient8: 'Mayonnaise',
      strIngredient9: 'White Wine Vinegar',
      strIngredient10: 'Pepper',
      strIngredient11: 'Mustard',
      strIngredient12: 'Onion Salt',
      strIngredient13: 'Garlic Powder',
      strIngredient14: 'Paprika',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '400g',
      strMeasure2: '2 tbs',
      strMeasure3: '2',
      strMeasure4: 'Chopped',
      strMeasure5: '1/4 ',
      strMeasure6: '2 sliced',
      strMeasure7: '2 large',
      strMeasure8: '1 cup ',
      strMeasure9: '2 tsp',
      strMeasure10: 'Pinch',
      strMeasure11: '2 tsp',
      strMeasure12: '1 1/2 tsp ',
      strMeasure13: '1 1/2 tsp ',
      strMeasure14: '1/2 tsp',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://www.delicious.com.au/recipes/finally-recipe-worlds-top-selling-burger-big-mac/5221ee4a-279e-4a0b-8629-f442dc46822e',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '53018',
      strMeal: 'Bigos (Hunters Stew)',
      strDrinkAlternate: null,
      strCategory: 'Pork',
      strArea: 'Polish',
      strInstructions: 'Preheat the oven to 350 degrees F (175 degrees C)...',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/md8w601593348504.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=Oqg_cO4s8ik',
      strIngredient1: 'Bacon',
      strIngredient2: 'Kielbasa',
      strIngredient3: 'Pork',
      strIngredient4: 'Flour',
      strIngredient5: 'Garlic',
      strIngredient6: 'Onion',
      strIngredient7: 'Mushrooms',
      strIngredient8: 'Cabbage',
      strIngredient9: 'Sauerkraut',
      strIngredient10: 'Red Wine',
      strIngredient11: 'Bay Leaf',
      strIngredient12: 'Basil',
      strIngredient13: 'Marjoram',
      strIngredient14: 'Paprika',
      strIngredient15: 'Caraway Seed',
      strIngredient16: 'Hotsauce',
      strIngredient17: 'Beef Stock',
      strIngredient18: 'Tomato Puree',
      strIngredient19: 'Diced Tomatoes',
      strIngredient20: 'Worcestershire Sauce',
      strMeasure1: '2 sliced',
      strMeasure2: '1 lb',
      strMeasure3: '1 lb',
      strMeasure4: '1/4 cup',
      strMeasure5: '3 chopped',
      strMeasure6: '1 Diced',
      strMeasure7: '1 1/2 cup ',
      strMeasure8: '4 cups ',
      strMeasure9: '1 Jar',
      strMeasure10: '1/4 cup',
      strMeasure11: '1',
      strMeasure12: '1 tsp ',
      strMeasure13: '1 tsp ',
      strMeasure14: '1 tbs',
      strMeasure15: '1/8 teaspoon',
      strMeasure16: '1 dash',
      strMeasure17: '5 Cups',
      strMeasure18: '2 tbs',
      strMeasure19: '1 cup ',
      strMeasure20: '1 dash',
      strSource: 'https://www.allrecipes.com/recipe/138131/bigos-hunters-stew/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};

export const firstLetterFood = {
  meals: [
    {
      idMeal: '52768',
      strMeal: 'Apple Frangipan Tart',
      strDrinkAlternate: null,
      strCategory: 'Dessert',
      strArea: 'British',
      strInstructions: 'Preheat the oven to 200C/180C Fan/Gas 6...',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/wxywrq1468235067.jpg',
      strTags: 'Tart,Baking,Fruity',
      strYoutube: 'https://www.youtube.com/watch?v=rp8Slv4INLk',
      strIngredient1: 'digestive biscuits',
      strIngredient2: 'butter',
      strIngredient3: 'Bramley apples',
      strIngredient4: 'butter, softened',
      strIngredient5: 'caster sugar',
      strIngredient6: 'free-range eggs, beaten',
      strIngredient7: 'ground almonds',
      strIngredient8: 'almond extract',
      strIngredient9: 'flaked almonds',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: '175g/6oz',
      strMeasure2: '75g/3oz',
      strMeasure3: '200g/7oz',
      strMeasure4: '75g/3oz',
      strMeasure5: '75g/3oz',
      strMeasure6: '2',
      strMeasure7: '75g/3oz',
      strMeasure8: '1 tsp',
      strMeasure9: '50g/1¾oz',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource: null,
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52893',
      strMeal: 'Apple & Blackberry Crumble',
      strDrinkAlternate: null,
      strCategory: 'Dessert',
      strArea: 'British',
      strInstructions: 'Heat oven to 190C/170C fan/gas 5. Tip the flour and sugar...',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/xvsurr1511719182.jpg',
      strTags: 'Pudding',
      strYoutube: 'https://www.youtube.com/watch?v=4vhcOwVBDO4',
      strIngredient1: 'Plain Flour',
      strIngredient2: 'Caster Sugar',
      strIngredient3: 'Butter',
      strIngredient4: 'Braeburn Apples',
      strIngredient5: 'Butter',
      strIngredient6: 'Demerara Sugar',
      strIngredient7: 'Blackberrys',
      strIngredient8: 'Cinnamon',
      strIngredient9: 'Ice Cream',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '120g',
      strMeasure2: '60g',
      strMeasure3: '60g',
      strMeasure4: '300g',
      strMeasure5: '30g',
      strMeasure6: '30g',
      strMeasure7: '120g',
      strMeasure8: '¼ teaspoon',
      strMeasure9: 'to serve',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://www.bbcgoodfood.com/recipes/778642/apple-and-blackberry-crumble',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};

export const ingredientDrink = {
  oi: 'oi',
};

export const nameDrink = {};
export const firstLetterDrink = {};
