export const ingredientFood = {
  meals: [
    {
      strMeal: 'Big Mac',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/urzj1d1587670726.jpg',
      idMeal: '53013',
    },
    {
      strMeal: 'Cream Cheese Tart',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/wurrux1468416624.jpg',
      idMeal: '52779',
    }],
};

export const nameFood = {
  meals: [
    {
      idMeal: '53013',
      strMeal: 'Big Mac',
      strDrinkAlternate: null,
      strCategory: 'Beef',
      strArea: 'American',
      strInstructions: 'For the Big Mac sauce, combine all the ingredients in...',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/urzj1d1587670726.jpg',
      strSource: 'https://www.delicious.com.au/recipes/finally-recipe-worlds-top-selling-burger-big-mac/5221ee4a-279e-4a0b-8629-f442dc46822e',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '53018',
      strMeal: 'Bigos (Hunters Stew)',
      strDrinkAlternate: null,
      strCategory: 'Pork',
      strArea: 'Polish',
      strInstructions: 'Preheat the oven to 350 degrees F (175 degrees C)...',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/md8w601593348504.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=Oqg_cO4s8ik',
      strSource: 'https://www.allrecipes.com/recipe/138131/bigos-hunters-stew/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};

export const firstLetterFood = {
  meals: [
    {
      idMeal: '52768',
      strMeal: 'Apple Frangipan Tart',
      strDrinkAlternate: null,
      strCategory: 'Dessert',
      strArea: 'British',
      strInstructions: 'Preheat the oven to 200C/180C Fan/Gas 6...',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/wxywrq1468235067.jpg',
      strTags: 'Tart,Baking,Fruity',
      strYoutube: 'https://www.youtube.com/watch?v=rp8Slv4INLk',
      strIngredient1: 'digestive biscuits',
      strSource: null,
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52893',
      strMeal: 'Apple & Blackberry Crumble',
      strDrinkAlternate: null,
      strCategory: 'Dessert',
      strArea: 'British',
      strInstructions: 'Heat oven to 190C/170C fan/gas 5. Tip the flour and sugar...',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/xvsurr1511719182.jpg',
      strTags: 'Pudding',
      strYoutube: 'https://www.youtube.com/watch?v=4vhcOwVBDO4',
      strSource: 'https://www.bbcgoodfood.com/recipes/778642/apple-and-blackberry-crumble',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};

export const ingredientDrink = {
  drinks: [
    {
      strDrink: '155 Belmont',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/yqvvqs1475667388.jpg',
      idDrink: '15346',
    },
    {
      strDrink: '501 Blue',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/ywxwqs1461867097.jpg',
      idDrink: '17105',
    },
  ],
};

export const nameDrink = {
  drinks: [
    {
      idDrink: '12770',
      strDrink: 'Iced Coffee',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Coffee / Tea',
      strIBA: null,
      strAlcoholic: 'Non alcoholic',
      strGlass: 'Coffee mug',
      strInstructions: 'Mix together until coffee and sugar is dissolved. Add milk...',
      strInstructionsES: null,
      strInstructionsDE: 'Zusammenmischen, ...',
      strInstructionsFR: null,
      strInstructionsIT: 'Mescolare fino a quando ...',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/ytprxy1454513855.jpg',
      strIngredient1: 'Coffee',
      strIngredient2: 'Sugar',
      strIngredient3: 'Water',
      strIngredient4: 'Milk',
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-02-03 15:37:35',
    },
    {
      idDrink: '12782',
      strDrink: 'Thai Coffee',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Coffee / Tea',
      strIBA: null,
      strAlcoholic: 'Non alcoholic',
      strGlass: 'Highball glass',
      strInstructions: 'Place the coffee ...',
      strInstructionsES: null,
      strInstructionsDE: 'Geben Sie den Kaffee und ...',
      strInstructionsFR: null,
      strInstructionsIT: 'Metti il caffè e le spezie nel ...',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/wquwxs1441247025.jpg',
      strIngredient1: 'Coffee',
      strIngredient2: 'Coriander',
      strIngredient3: 'Cardamom',
      strIngredient4: 'Sugar',
      strIngredient5: 'Whipping cream',
      strIngredient6: 'Ice',
      strIngredient7: null,
      strIngredient8: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2015-09-03 03:23:45',
    },
  ],
};

export const firstLetterDrink = {
  drinks: [
    {
      idDrink: '17222',
      strDrink: 'A1',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Cocktail',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Cocktail glass',
      strInstructions: 'Pour all ingredients into a ...',
      strInstructionsES: 'Vierta todos los ....',
      strInstructionsFR: null,
      strInstructionsIT: 'Versare tutti...',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/2x8thr1504816928.jpg',
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-07 21:42:09',
    },
    {
      idDrink: '13501',
      strDrink: 'ABC',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Shot',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Shot glass',
      strInstructions: 'Layered in a shot glass.',
      strInstructionsES: 'Coloque todos los ingredientes en un vaso de chupito.',
      strInstructionsDE: 'Schichtaufbau in einem Schnapsglas.',
      strInstructionsFR: null,
      strInstructionsIT: 'Versa in ordine di lettera ...',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/tqpvqp1472668328.jpg',
      strIngredient1: 'Amaretto',
      strIngredient2: 'Baileys irish cream',
      strIngredient3: 'Cognac',
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-08-31 19:32:08',
    },
  ],
};

export const abcDrink = {
  drinks: [
    {
      idDrink: '13501',
      strDrink: 'ABC',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Shot',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Shot glass',
      strInstructions: 'Layered in a shot glass.',
      strInstructionsES: 'Coloque todos los ingredientes en un vaso de chupito.',
      strInstructionsDE: 'Schichtaufbau in einem Schnapsglas.',
      strInstructionsFR: null,
      strInstructionsIT: 'Versa in ordine...',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/tqpvqp1472668328.jpg',
      strIngredient1: 'Amaretto',
      strIngredient2: 'Baileys irish cream',
      strIngredient3: 'Cognac',
      strIngredient4: null,
      strMeasure1: '1/3 ',
      strMeasure2: '1/3 ',
      strMeasure3: '1/3 ',
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-08-31 19:32:08',
    },
  ],
};
